# Generated by Django 4.2.26 on 2026-04-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField(max_length=2000)),
                ('ingredients_json', models.JSONField(default=list)),
                ('servings', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_of'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_recipes', to='api.weeklyplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_uses', to='api.savedrecipe')),
            ],
            options={
                'unique_together': {('plan', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='recipes',
            field=models.ManyToManyField(through='api.WeeklyPlanRecipe', to='api.savedrecipe'),
        ),
    ]
