# Generated by Django 4.2.30 on 2026-04-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pantryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(default='other', max_length=50)),
                ('checked', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='api.weeklyplan')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
