# Generated by Django 4.2.30 on 2026-04-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weeklygroceryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='instructions_json',
            field=models.JSONField(default=list),
        ),
    ]
