# Generated by Django 4.2.30 on 2026-09-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_watchlisturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklygroceryitem',
            name='recipe_indices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='merged_from_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='weeklyplanrecipe',
            name='multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='CartRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=50)),
                ('added', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('unmatched_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_runs', to='api.weeklyplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
